config/routes.rb
Rails.application.routes.draw do
	root "users#index"
  resources :users
end

app/models/post.rb
class Post < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
	has_many :posts
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
	
	def index

		@users = User.all

		def show
			@user = User.find_by_id(params[:id])
		end

	end

end

app/controllers/users_controller.rb
class UsersController <ApplicationController

	def index
		@users = User.all

		if @users.present?
			flash[:notice] = "Users exist!"
		else
			flash[:alert] = "Sorry, there were no users to display"
		end

	end

	def show
		@post = Post.find_by_id(params[:id])

		if @post.present?
			flash[:notice] = "Post exists"
		else
			flash[:alert] = "Sorry, there were no posts to display"
		end
	end

	def new
		@user = User.new
		@post = Post.new
	end

	def create

		@post = Post.new(post_params)
		@user = User.new(user_params)

		if @post.save
			flash[:notice] = "Post was successfully created"
			redirect_to users_path
		else
			render :new
		end
	end

	def destroy
		user = User.find(params[:id])
		if user.delete
			flash[:notice] = "User Deleted"
		else
			flash[:alert] = "Could not delete user"
		end

		return redirect_to(users_path)
	end

	def user_params
		params.require(:user).permit(:fname, :lname, :email)
	end
	def post_params
		params.require(:post).permit(:body)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper

	def list_users(users)
		out = "<ul>"
		@users.each do |user|
			out += "<li>"
			out += "#{user.fname} #{user.lname} &ndash;"
			out += link_to("Delete User", user_path(user.id), method: :delete)
			out += "</li>"
		end

		out += "</ul>".html_safe
		return out.html_safe
	end
end

app/views/home/index.html.erb
<h1>Blog Forum</h1>

<%= list_users(@users) %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= flash[:notice] if flash[:notice] %>


<%= yield %>

</body>
</html>

app/views/users/index.html.erb
<h1>Blog Forum</h1>
<%= button_to "Add New Blog Post", new_user_path, method: :get %>

<%= list_users(@users) %>

app/views/users/new.html.erb
<h1>Add New Post</h1>
<%= form_for @user do |f| %>
	<div>
		<%= f.label :fname %>
		<%= f.text_field :fname %>
	</div>
	<div>
		<%= f.label :lname %>
		<%= f.text_field :lname %>
	</div>
	<div>
		<%= f.label :email %>
		<%= f.text_field :email %>
	</div>
	<hr />
	<%= fields_for @post do |p| %>
		<div>
			<%= p.label :body %>
			<%= p.text_area :body, size: "60X12" %>
		</div>
	<% end %>
	<div>
		<%= f.submit %>
	</div>

<% end %>

app/views/users/post.html.erb
<h1>Blog Post Detail</h1>
<ul>
	<li>POST: <%= @post.body %></li>
	<li>POST ID: <%= @post.id %></li>
	<li>CREATED: <%= @post.created_at %></li>
	<li>USER ID:  <%= @post.user_id %></li>
	<li>FIRST NAME: <%= @post.user.fname %></li>
	<li>LAST NAME:  <%= @post.user.lname %></li>
</ul>

app/views/users/posts.html.erb
<h1>Blog Posts</h1>
<ul>
	<% @posts.each do |post| %>
		<li><%= post.body %> Posted by: <%= post.user.fname %> <%= post.user.lname %></li>

	<% end %>
</ul>

app/views/users/show.html.erb
<h1>Blog Post Detail</h1>

<% if @post %>

<ul>
	<li>POST: <%= @post.body %></li>
	<li>POST ID: <%= @post.id %></li>
	<li>CREATED: <%= @post.created_at %></li>
	<li>USER ID:  <%= @post.user_id %></li>
	<li>FIRST NAME: <%= @post.user.fname %></li>
	<li>LAST NAME:  <%= @post.user.lname %></li>
</ul>
<% else %>
	<%= flash[:alert] if flash[:alert] %>
<% end %>